### PR TITLE
WindowsFeature: Added catch for RuntimeException to ignore and updated tests (same changes as PR #267).

### PR DESCRIPTION
**Pull request by corydwood**
Same changes as [PR #267](https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/267).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/7)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@corydwood I'm working on fixing these test failures. It doesn't have anything to do with your code. The failure is from a common test that was added recently. It attempts to check the module manifest. The module manifest for this module requires WMF 5.1, but AppVeyor does not have a WMF 5.1 image yet so the test is erroring out on the WMF 5.0 machine.

I'm working on fixing this in [my fork](https://github.com/kwirkykat/psDscResources/tree/InstallWMF5Dot1). I got WMF 5.1 installed on the AppVeyor machine, but now the [integration tests are complaining](https://ci.appveyor.com/project/KatieKeim/psdscresources) about overwriting in-box resources. These errors in the integration tests are only occurring on AppVeyor, but not when we run the tests manually. I'm investigating our common tests to see if they are causing the AppVeyor problem. I'll keep you posted if I figure anything out.

**Comment by kwirkykat** [comment]
@corydwood All done. Rebase onto dev and you should be good

**Comment by kwirkykat** [comment]
@corydwood Please change this to a rebase instead of a merge.

When you do a merge (`git merge`), the commits you are missing from the branch you specify are added *after* your changes and hence are included in the PR (and it looks like you made these changes). When you do a rebase (`git rebase`), the commits you are missing from the branch you specify are added *before* your changes (and before the PR), so then they would not show up in this PR.

You can fix this in your branch with the following commands.

1. Reset the HEAD of your dev branch back to your commit:  
`git reset faf923d6a1676e3012c54d19d76b881f4b3b28ce --hard`
2. Set up this repo as your upstream remote (if you haven't already):  
` git remote add upstream https://github.com/PowerShell/PSDscResources`
3. Fetch any changes that have happened in the upstream repository recently:  
` git fetch upstream`
4. Rebase onto the upstream dev branch:  
`git rebase upstream/dev`
4. Force push the updates to your branch:  
`git push origin dev --force`

**Comment by kwirkykat** [comment]
@corydwood Thanks for doing the rebase :+1:

I'm worried that catching the error is going to let other errors slip through.
I'm not sure how to reproduce this error on my machine, but have you tried this approach instead?

```powershell
$serverManagerModule = Get-Module -Name 'ServerManager'

if ($null -eq $serverManagerModule)
{
    try
    {
        Import-Module -Name 'ServerManager' -ErrorAction 'Stop'
    }
    catch
    {
        Write-Verbose -Message $script:localizedData.ServerManagerModuleNotFoundMessage
        New-InvalidOperationException -Message $script:localizedData.SkuNotSupported
    }
}
```

For any others wondering what issue is trying to be fixed here: https://social.technet.microsoft.com/Forums/en-US/9fc314e1-27bf-4f03-ab78-5e0f7a662b8f/importmodule-servermanager-some-or-all-identity-references-could-not-be-translated?forum=winserverpowershell

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/7#-:-KWoDgreaY0IdXnKd0M5:byxfjud)*

**Comment by corydwood** [comment]
The error occurs when importing the ServerManager module, so the code you listed will still throw the error that will cause the DSC resource to fail the test. The change I made is only catching the error if the message is **Some or all identity references could not be translated**. If the message is something else, it's handled the same way it was before my change.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/7#-:-KWoL0EnWb1q0D_yj_YD:b1xbot6)*

**Comment by kwirkykat** [comment]
Ok. Then this looks good to me. Just some tiny wording comments

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 229 at r3](https://reviewable.io:443/reviews/powershell/psdscresources/7#-KWpCpDy75xw6suePpDC:-KWpCpDzGYycbc5q7GNJ:b-ny9u6r) ([raw file](https://github.com/powershell/psdscresources/blob/049cf995374c9b45a970bd22174408cf30fccad5/README.md#L229)):*
> This solved the same issue that [PR #267](https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/267) solved.

Can you add a short description of the issue here (or the link I gave above) instead of referencing a GitHub issue?
It will help those who only look at release notes on PS Gallery.

---

*[Tests/Unit/MSFT_WindowsFeature.Tests.ps1, line 584 at r3](https://reviewable.io:443/reviews/powershell/psdscresources/7#-KWpCGTD1PhrFTGYKV6w:-KWpCGTD1PhrFTGYKV6x:b-kkc2mw) ([raw file](https://github.com/powershell/psdscresources/blob/049cf995374c9b45a970bd22174408cf30fccad5/Tests/Unit/MSFT_WindowsFeature.Tests.ps1#L584)):*
> Should Not Throw when exception is Identity Reference Runtime Exception

Remove extra capitalization: 'Should not throw when exception is Identity Reference Runtime Exception'
(I know the one above doesn't follow this properly)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/7#-:-KWpCDLdPN-njJ5VYPqU:bf85m1m)*

**Comment by corydwood** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 229 at r3](https://reviewable.io:443/reviews/powershell/psdscresources/7#-KWpCpDy75xw6suePpDC:-KXS8XddtqclDqyAjZHG:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/049cf995374c9b45a970bd22174408cf30fccad5/README.md#L229)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > This solved the same issue that [PR #267](https://github.com/PowerShell/xPSDesiredStateConfiguration/pull/267) solved.
> 
> Can you add a short description of the issue here (or the link I gave above) instead of referencing a GitHub issue?
> It will help those who only look at release notes on PS Gallery.
</details>
Done.

---

*[Tests/Unit/MSFT_WindowsFeature.Tests.ps1, line 584 at r3](https://reviewable.io:443/reviews/powershell/psdscresources/7#-KWpCGTD1PhrFTGYKV6w:-KXS8WoRQpSOXlIN5QIP:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/049cf995374c9b45a970bd22174408cf30fccad5/Tests/Unit/MSFT_WindowsFeature.Tests.ps1#L584)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > Should Not Throw when exception is Identity Reference Runtime Exception
> 
> Remove extra capitalization: 'Should not throw when exception is Identity Reference Runtime Exception'
> (I know the one above doesn't follow this properly)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/7)*

**Comment by TravisEz13** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1, line 523 at r4](https://reviewable.io:443/reviews/powershell/psdscresources/7#-KXmQbPgj54BFv9OzFs0:-KXmQbPgj54BFv9OzFs1:b9zbqyt) ([raw file](https://github.com/powershell/psdscresources/blob/6bbd48cc29f8165c7295fcea10072b5b6c7b0e37/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1#L523)):*
> ```PowerShell
>         if ($_.Exception.Message -like "*Some or all identity references could not be translated*")
>         {
>             Write-Verbose $_.Exception.Message
> ```

The message should be formatted something like 
`"Error importing 'ServerManager' module: {0}" -f $_.Exception.Message`
But the format string should come from localizedData

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/7)*

**Comment by kwirkykat** [comment]
@corydwood I'm going to close this PR and then re-open it immediately to see if the Microsoft CLA bot is working on this repo now.

**Comment by corydwood** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1, line 523 at r4](https://reviewable.io:443/reviews/powershell/psdscresources/7#-KXmQbPgj54BFv9OzFs0:-KY-wo-o4pXnfNkp8YtE:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/6bbd48cc29f8165c7295fcea10072b5b6c7b0e37/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1#L523)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary><blockquote>

The message should be formatted something like 
`"Error importing 'ServerManager' module: {0}" -f $_.Exception.Message`
But the format string should come from localizedData
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/7)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/7)*

**Comment by TravisEz13** [comment]
:lgtm: but I don't have permissions to merge

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/7#-:-KY0bpp2Fz4u_dQvlW-c:b-80fyfi)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/7#-:-KYGCTkt-DFqTTZmAVmh:bnfp4nl)*

**Pull request merged**
