### PR TITLE
Add description of changes to MsiPackage resource into README file

### PR DESCRIPTION
**Pull request by duracellko**
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/55)

### CODE REVIEW

**Comment by mbreakey3** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[README.md, line 585 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/55#-KiI3ei4_9JQQvCWSvTI:-KiI3ei4_9JQQvCWSvTJ:b-9un5h) ([raw file](https://github.com/powershell/psdscresources/blob/63a439723c86df20bbadb156498f1ec2f78b5b02/README.md#L585)):*
> ```Markdown
>     * Fixed a minor bug in the unit tests where sometimes the incorrect DateTime format was used.
> * Added MsiPackage
> 	* Parse installation date from registry using invariant culture.
> ```

Can you move these two comments up under the 'Unreleased' section? - these are the notes from the last release. Otherwise, this looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/55)*

**Comment by mbreakey3** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/55#-:-KiVzwcuOwSGfCwfVJDA:bnfp4nl)*

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/55#-:-KiW2qw6B-4NC2_mHz8H:bnfp4nl)*

**Comment by mbreakey3** [comment]
Will merge once AppVeyor passes

**Comment by duracellko** [comment]
Thank you for guidance.

**Pull request merged**
