### PR TITLE
Updating User

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/24)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 712 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWpWEtF2c9R-AdEBFP:-KbWpWEtF2c9R-AdEBFQ:b-y1pxgy) ([raw file](https://github.com/powershell/psdscresources/blob/b275db0f1c94dce251c99fbe969ec0e38d9bfc59/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L712)):*
> Set-StrictMode -Version Latest

Not needed since this is already turned on for the whole file

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 720 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWpS3BIdVIxm81yMnX:-KbWpS3Ceq_3CwwNEvJ4:b-cek6f6) ([raw file](https://github.com/powershell/psdscresources/blob/b275db0f1c94dce251c99fbe969ec0e38d9bfc59/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L720)):*
> -ErrorAction 'Stop'

Not needed since you have `$errorActionPreference = 'Stop'` for the whole file.

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 742 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWpd6YuyEtPVEIaQ0L:-KbWpd6YuyEtPVEIaQ0M:b3ga5p8) ([raw file](https://github.com/powershell/psdscresources/blob/b275db0f1c94dce251c99fbe969ec0e38d9bfc59/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L742)):*
> return $returnValue

Can you put the return after the catch and assign the hashtable you return in the catch to the same variable so that we have a single point of return?

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 849 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWpo-Vc9UU2AZDOsr2:-KbWpo-Vc9UU2AZDOsr3:b-mq4yew) ([raw file](https://github.com/powershell/psdscresources/blob/b275db0f1c94dce251c99fbe969ec0e38d9bfc59/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L849)):*
> -ErrorAction 'Stop'

Not needed

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 1031 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWpv0d27_0Vf698SXk:-KbWpv0d27_0Vf698SXl:bdr0uu4) ([raw file](https://github.com/powershell/psdscresources/blob/b275db0f1c94dce251c99fbe969ec0e38d9bfc59/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L1031)):*
> Set-StrictMode -Version Latest

Not needed

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 1038 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWptxbXm2O73D2YS2u:-KbWptxbXm2O73D2YS2v:b-mq4yew) ([raw file](https://github.com/powershell/psdscresources/blob/b275db0f1c94dce251c99fbe969ec0e38d9bfc59/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L1038)):*
> -ErrorAction 'Stop'

Not needed

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 1050 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWq1HsBHUhlxp3alY-:-KbWq1HsBHUhlxp3alY0:b-76vakg) ([raw file](https://github.com/powershell/psdscresources/blob/b275db0f1c94dce251c99fbe969ec0e38d9bfc59/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L1050)):*
> # The user is not found
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>
>             if ($Ensure -eq 'Absent')
>             {
>                 return $true
>             }
>             else
>             {
>                 return $false
>             }
</details>

return ($Ensure -eq 'Absent')

---

*[Tests/Unit/MSFT_UserResource.Tests.ps1, line 743 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWtxfUyXnXqQ7IyiEU:-KbWtxfVBG3a-fMsC6Z6:bwzxw7z) ([raw file](https://github.com/powershell/psdscresources/blob/b275db0f1c94dce251c99fbe969ec0e38d9bfc59/Tests/Unit/MSFT_UserResource.Tests.ps1#L743)):*
> 'Should throw an Invalid Operation exception'

When?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/24)*

**Comment by kwirkykat** [comment]
Reviewed 1 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/24)*

**Comment by mbreakey3** [comment]
Review status: 5 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 1050 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWq1HsBHUhlxp3alY-:-KbXBwKum8Kqyl3nFBV4:b3kre) ([raw file](https://github.com/powershell/psdscresources/blob/b275db0f1c94dce251c99fbe969ec0e38d9bfc59/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L1050)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> # The user is not found
>             if ($Ensure -eq 'Absent')
>             {
>                 return $true
>             }
>             else
>             {
>                 return $false
>             }

return ($Ensure -eq 'Absent')
</blockquote></details>

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/24)*

**Comment by kwirkykat** [comment]
Reviewed 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 1050 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWq1HsBHUhlxp3alY-:-KbXQhehHRwrLHND8AeK:bonq4bv) ([raw file](https://github.com/powershell/psdscresources/blob/eed85795ee6f9abfd2dae52447d857a9717dc2eb/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L1050)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

?
</blockquote></details>

Instead of checking the value of the boolean ($Ensure -eq 'Absent') to return true if it is true and false if is false, you can just return the boolean ($Ensure -eq 'Absent')

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/24)*

**Comment by mbreakey3** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[DscResources/MSFT_UserResource/MSFT_UserResource.psm1, line 1050 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/24#-KbWq1HsBHUhlxp3alY-:-KbXRe7cFUJjJjarqBT5:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/eed85795ee6f9abfd2dae52447d857a9717dc2eb/DscResources/MSFT_UserResource/MSFT_UserResource.psm1#L1050)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

Instead of checking the value of the boolean ($Ensure -eq 'Absent') to return true if it is true and false if is false, you can just return the boolean ($Ensure -eq 'Absent')
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/24)*

**Comment by kwirkykat** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/24)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/24#-:-KbXS6_8WbYaENguPZvQ:bnfp4nl)*

**Pull request merged**
