### PR TITLE
Add Archive resource

### PR DESCRIPTION
**Pull request by kwirkykat**
Adding the cleaned Archive resource.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/41)

### CODE REVIEW

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 19 of 19 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/MSFT_Archive.EndToEnd.Tests.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/41#-KdcMyvJw5v67dGej6mt:-KdcMyvJw5v67dGej6mu:b9ishbt) ([raw file](https://github.com/powershell/psdscresources/blob/5a1109753ae6b59fcfa0f36c41c0f1f673fb9444/Tests/Integration/MSFT_Archive.EndToEnd.Tests.ps1#L3)):*
> ```PowerShell
> $errorActionPreference = 'Stop'
> Set-StrictMode -Version 'Latest'
> ```

Should we still add in the 'if not on 5.1' check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/41#-:-KdcR-dOIUek-v0kjj83:bnfp4nl)*

**Comment by mbreakey3** [comment]
Just had the comment about the integration tests still requiring the 5.1 check or not

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/41#-:-KdcRD9BKjPdLbswSPkg:b-t449es)*

**Comment by kwirkykat** [comment]
Review status: 17 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/MSFT_Archive.EndToEnd.Tests.ps1, line 3 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/41#-KdcMyvJw5v67dGej6mt:-KdcRfa-f4v9rlR7QSuE:bgwmve8) ([raw file](https://github.com/powershell/psdscresources/blob/5a1109753ae6b59fcfa0f36c41c0f1f673fb9444/Tests/Integration/MSFT_Archive.EndToEnd.Tests.ps1#L3)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

Should we still add in the 'if not on 5.1' check?
</blockquote></details>

Added it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/41)*

**Comment by mbreakey3** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/41)*

**Pull request merged**
