### PR TITLE
Opt-In to Meta Test - Fixes #172

### LINKED ISSUE #172: Opt In to Analyzer Rules and Resolve any issues
This module is not currently opted into any of the PSSA rules:
        "Common Tests - Required Script Analyzer Rules",
        "Common Tests - Flagged Script Analyzer Rules",
        "Common Tests - New Error-Level Script Analyzer Rules",
        "Common Tests - Custom Script Analyzer Rules"

We should opt it in and fix any identified issues. I'd suggest doing one at a time as there are most likely a number of issues.

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR opts in to Meta Tests and resolves any issue identified.

#### This Pull Request (PR) fixes the following issues

- Fixes #172

#### Task list

- [x] Added an entry under the Unreleased section in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@mhendric - could you review this one for me when you get time?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/173)

### CODE REVIEW

**Review by mhendric — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/psdscresources/173)* status: 6 of 12 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[DscResources/GroupSet/GroupSet.schema.psm1, line 35 at r1](https://reviewable.io/reviews/powershell/psdscresources/173#-Lr9q31U8ngF2AHQbl89:-Lr9q31V2A6ikIN1U3-E:b-u4wf0q) ([raw file](https://github.com/powershell/psdscresources/blob/a5ad84040b3b3eac4a60b354f5cbd7286b3bf17d/DscResources/GroupSet/GroupSet.schema.psm1#L35)):*
> ```
> configuration GroupSet
> ```
Is the change to lowercase c for Configuration intentional here (and throughout)? As best I can tell, the configuration keyword should start with a capital letter. https://docs.microsoft.com/en-us/powershell/scripting/dsc/configurations/configurations?view=powershell-6

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/psdscresources/173)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @mhendric)

___
*[DscResources/GroupSet/GroupSet.schema.psm1, line 35 at r1](https://reviewable.io/reviews/powershell/psdscresources/173#-Lr9q31U8ngF2AHQbl89:-LrwuzDX8lnoMhQO_uIr:bet04ev) ([raw file](https://github.com/powershell/psdscresources/blob/a5ad84040b3b3eac4a60b354f5cbd7286b3bf17d/DscResources/GroupSet/GroupSet.schema.psm1#L35)):*
<details><summary><i>Previously, mhendric (Mike Hendrickson) wrote…</i></summary><blockquote>

> ```
> configuration GroupSet
> ```
Is the change to lowercase c for Configuration intentional here (and throughout)? As best I can tell, the configuration keyword should start with a capital letter. https://docs.microsoft.com/en-us/powershell/scripting/dsc/configurations/configurations?view=powershell-6
</blockquote></details>

Fixed. Thanks @mhendric !

**Comment by mhendric** [comment]
Hey @PlagueHO. Looks like you got a CI failure. Ping me once this is ready for a final review. Thanks.

Custom DSC Resource Kit PSSA rule(s) did not pass.
971
The following PSScriptAnalyzer rule 'DscResource.AnalyzerRules\Measure-Keyword' errors need to be fixed:
972
GroupSet.schema.psm1 (Line 35): 'Configuration' statements should not contain upper case letters See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-keywords
973
For instructions on how to run PSScriptAnalyzer on your own machine, please go to https://github.com/powershell/PSScriptAnalyzer
974
      [-] Should pass all custom DSC Resource Kit PSSA rules 808ms
975
        Expected $null, but got Microsoft.Windows.PowerShell.ScriptAnalyzer.Generic.DiagnosticRecord.
976
        582:                         $customPssaRulesOutput | Should -Be $null
977
        at <ScriptBlock>, C:\projects\psdscresources\DscResource.Tests\Meta.Tests.ps1: line 582

**Comment by PlagueHO** [comment]
@johlju - the current DSCResource.Tests require a lower case 'c' to be used for the `Configuration` keyword - this makes sense because it is a keyword and we've enforced lower case letters for all keywords.

However, looking through most repos, we're not doing this (e.g. see Examples).

Two things jump to mind here:
1. We need to define if we are including `Configuration` as a keyword that should be all lower case.
2. We need to apply our code style tests to examples.

What is your opinion on this? I'd prefer to use lower case 'c' for configuration for standardization- but it will have an impact if we extend style tests to examples.

cc @SSvilen

**Comment by PlagueHO** [comment]
Hi @mhendric - we added a bunch of code style tests a while back that validate all keywords are all lower case. As "Configuration" is a keyword it is being caught in this test. Only just encountered this because most other repos don't have "Configuration" in the modules folder - and we're not scanning the Examples or Tests for code style (the other places "Configuration" is used). So we'll need to decide whether we want to eliminate "Configuration" from the list of keywords.

My preference would be standardization: All keywords all lower case (makes it easier to remember ;) ).

**Comment by johlju** [comment]
I had the same problem in another module. I just change the code to use lower-case ‘c’ since I also thought it best to have one standard, all keywords lower-case. I think we should change all the configuration blocks to use lower-case ‘c’.

**Comment by mhendric** [comment]
Hey Guys, I'm a bit concerned that if we mandate a casing for this that is not the default casing, we're going to be hitting this issue anytime someone's IDE (correctly) autocompletes 'configuration' to 'Configuration'. Not to mention every DSC module is going to have to be updated to use an incorrect case for this keyword. Thoughts?

**Review by SSvilen — COMMENTED** [review]
@mhendric I believe you are right . The Configuration word is not listed [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_language_keywords?view=powershell-5.1). I believe it's because it is DSC specific. 

> *[Reviewable](https://reviewable.io/reviews/powershell/psdscresources/173#-:-Lrzbe0M7dr9W3xEO9IV:b-ir6lip)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @mhendric)

**Comment by mhendric** [comment]
@SSvilen , good catch. That wasn't exactly what I was getting at, but I think you are right that Configuration is DSC specific. Further, our official documentation of it shows it with a capital C:

https://docs.microsoft.com/en-us/powershell/scripting/dsc/configurations/configurations?view=powershell-6

**Comment by mhendric** [comment]
Looks like another related DSC keyword is 'Node'. At least in the PowerShell ISE, that keyword autocompletes with a capital N as well.

**Comment by SSvilen** [comment]
If everyone agrees I can remove all DSC related keywords from the check.

**Comment by johlju** [comment]
@SSvilen lets make an exception for the keywords `Configuration` and `Node`. They will autocomplete in VS Code, but not the keyword `function` for example. So those two keywords can be written with first letter as lower-case or upper-case. If possible add an array with these two keywords if there are more in the future we need to make an exception for. 

It will be less code to change, and we can change that to also have lower-case in the future.

/cc @PlaugeHO

**Comment by PlagueHO** [comment]
@SSvilen - :+1: from me - sorry for taking so long to get back. Will be a bit slow to respond for the next few weeks but will try and keep on top of things.

**Comment by SSvilen** [comment]
The [PR](https://github.com/PowerShell/DscResource.Tests/pull/352) has been submitted.

**Pull request closed without merging**
