### PR TITLE
Add set resources

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/18)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Reviewed 44 of 52 files at r1.
Review status: 44 of 52 files reviewed at latest revision, 8 unresolved discussions.

---

*[PSDscResources.psd1, line 76 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9bpnCjwLw8YAuI6WA:-KZ9bpnCjwLw8YAuI6WB:b-6m65zy) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/PSDscResources.psd1#L76)):*
> ```PowerShell
> 
> # DSC resources to export from this module
> DscResourcesToExport = 'Group', 'Script', 'Service', 'ServiceSet', 'User', 'WindowsFeature', 'WindowsFeatureSet', 'WindowsOptionalFeature', 'WindowsOptionalFeature', 'WindowsPackageCab', 'WindowsProcess', 'ProcessSet'
> ```

Missing GroupSet

---

*[README.md, line 40 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9c3H46REbxtIypmP7:-KZ9c3H46REbxtIypmP8:b-sy0oun) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/README.md#L40)):*
>  manage Service resources on a target node.

This part of Service should not be changed.

---

*[DscResources/GroupSet/GroupSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9cOHC60EP02gK3vVM:-KZ9cOHC60EP02gK3vVN:bgbovbw) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/GroupSet/GroupSet.psd1#L25)):*
> 4.0

5.1 since this is now overwriting an in-box?

---

*[DscResources/ProcessSet/ProcessSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9ceevRzrVpVb61eLy:-KZ9ceevRzrVpVb61eLz:b-s1lyby) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/ProcessSet/ProcessSet.psd1#L25)):*
> ```PowerShell
> 
> # Minimum version of the Windows PowerShell engine required by this module
> PowerShellVersion = '4.0'
> ```

5.1 since this is now overwriting an in-box?

---

*[DscResources/ServiceSet/ServiceSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9clz7RznEcUqsLIMI:-KZ9clz7RznEcUqsLIMJ:b-s1lyby) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/ServiceSet/ServiceSet.psd1#L25)):*
> ```PowerShell
> 
> # Minimum version of the Windows PowerShell engine required by this module
> PowerShellVersion = '4.0'
> ```

5.1 since this is now overwriting an in-box?

---

*[DscResources/WindowsFeatureSet/WindowsFeatureSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9cqOCi-jMi-ZbrHkn:-KZ9cqOCi-jMi-ZbrHko:b-s1lyby) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/WindowsFeatureSet/WindowsFeatureSet.psd1#L25)):*
> ```PowerShell
> 
> # Minimum version of the Windows PowerShell engine required by this module
> PowerShellVersion = '4.0'
> ```

5.1 since this is now overwriting an in-box?

---

*[DscResources/WindowsOptionalFeatureSet/WindowsOptionalFeatureSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9cvsjGVaku6IX0erQ:-KZ9cvsjGVaku6IX0erR:b-s1lyby) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/WindowsOptionalFeatureSet/WindowsOptionalFeatureSet.psd1#L25)):*
> ```PowerShell
> 
> # Minimum version of the Windows PowerShell engine required by this module
> PowerShellVersion = '4.0'
> ```

5.1 since this is now overwriting an in-box?

---

*[Tests/TestHelpers/MSFT_WindowsProcess.TestHelper.psm1, line 1 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9e1BVu9CXDmXsIWw8:-KZ9e1BWCVjiQI9cQpZ1:bimx4to) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/Tests/TestHelpers/MSFT_WindowsProcess.TestHelper.psm1#L1)):*
> ```PowerShell
> $errorActionPreference = 'Stop'
> ```

This file isn't needed anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/18)*

**Comment by mbreakey3** [comment]
Review status: 44 of 52 files reviewed at latest revision, 8 unresolved discussions.

---

*[PSDscResources.psd1, line 76 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9bpnCjwLw8YAuI6WA:-KZA0uQ6SIMMCNrfG9HH:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/PSDscResources.psd1#L76)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

Missing GroupSet
</blockquote></details>

Done.

---

*[README.md, line 40 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9c3H46REbxtIypmP7:-KZA11ew78Y0U_KOimlw:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/README.md#L40)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

>  manage Service resources on a target node.

This part of Service should not be changed.
</blockquote></details>

Done.

---

*[DscResources/GroupSet/GroupSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9cOHC60EP02gK3vVM:-KZA1DB2nfsnJh5D-Lxc:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/GroupSet/GroupSet.psd1#L25)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

> 4.0

5.1 since this is now overwriting an in-box?
</blockquote></details>

Done.

---

*[DscResources/ProcessSet/ProcessSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9ceevRzrVpVb61eLy:-KZA1Rri4PtjGHT9IVhu:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/ProcessSet/ProcessSet.psd1#L25)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

5.1 since this is now overwriting an in-box?
</blockquote></details>

Done.

---

*[DscResources/ServiceSet/ServiceSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9clz7RznEcUqsLIMI:-KZA1SvDrWJK6hOqGgwh:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/ServiceSet/ServiceSet.psd1#L25)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

5.1 since this is now overwriting an in-box?
</blockquote></details>

Done.

---

*[DscResources/WindowsFeatureSet/WindowsFeatureSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9cqOCi-jMi-ZbrHkn:-KZA1UyEiV70xb6QuDSY:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/WindowsFeatureSet/WindowsFeatureSet.psd1#L25)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

5.1 since this is now overwriting an in-box?
</blockquote></details>

Done.

---

*[DscResources/WindowsOptionalFeatureSet/WindowsOptionalFeatureSet.psd1, line 25 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9cvsjGVaku6IX0erQ:-KZA1VddWnqseVlEFtCS:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/DscResources/WindowsOptionalFeatureSet/WindowsOptionalFeatureSet.psd1#L25)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

5.1 since this is now overwriting an in-box?
</blockquote></details>

Done.

---

*[Tests/TestHelpers/MSFT_WindowsProcess.TestHelper.psm1, line 1 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/18#-KZ9e1BVu9CXDmXsIWw8:-KZA1cutekga8xDsEZkj:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/e909652c98370eeae559e489ef2899aee9f9a6b3/Tests/TestHelpers/MSFT_WindowsProcess.TestHelper.psm1#L1)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary><blockquote>

This file isn't needed anymore
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/18)*

**Comment by kwirkykat** [comment]
Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/18)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/18#-:-KZA2k_3alIQEIr6V_y_:bnfp4nl)*

**Pull request merged**
