### PR TITLE
PSDscResources: Update LICENSE file to match the Microsoft Open Source Team standard. Fixes Issue #120

### PR DESCRIPTION
**Pull request by timhaintz**
Fixes [Issue #120](https://github.com/PowerShell/PSDscResources/issues/120)

README.md updated.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/121)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Cheers @timhaintz - not sure when we will be able to get a merge, but hopefully not too long.

**Comment by timhaintz** [comment]
Ah, gets me every time! Sorry @PlagueHO . Have updated as requested above, the second line is 89 characters long, is that too long? Pushing now. Thanks, Tim.

**Comment by timhaintz** [comment]
@PlagueHO just noticed appveyor failed. Do you want me to pull from upstream again or is it something you can resolve?

**Comment by timhaintz** [comment]
@PlagueHO I've merged the upstream changes. Waiting for tests to run. Thanks, Tim.

**Comment by timhaintz** [comment]
Thanks @PlagueHO

**Pull request merged**
