### PR TITLE
Adding WindowsFeature

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/5)

### CODE REVIEW

**Comment by kwirkykat** [comment]
Can you also add this resource to the 'DscResourcesToExport' field in the module manifest (PSDscResources.psd1)?

---

Review status: 0 of 9 files reviewed at latest revision, 25 unresolved discussions.

---

*[README.md, line 1 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWasBIr_1JtEDRQslK:-KVWasBIr_1JtEDRQslL:bmfuaji) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/README.md#L1)):*
> ```Markdown
> [Build status](https://ci.appveyor.com/project/PowerShell/psdscresources/branch/dev)
> ```

This badge should represent the test status for the master branch (this is what all the other modules do.
OR I think it would actually be better to have both the master and the dev branch here so we could also easily see the status of the dev branch at any given time.

Like this:
```
master: [![Build status](https://ci.appveyor.com/api/projects/status/9uf3wyys7ky7776d/branch/dev?svg=true)](https://ci.appveyor.com/project/PowerShell/psdscresources/branch/master)

dev: [![Build status](https://ci.appveyor.com/api/projects/status/9uf3wyys7ky7776d/branch/dev?svg=true)](https://ci.appveyor.com/project/PowerShell/psdscresources/branch/dev)
```

---

*[README.md, line 150 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWc_7bhwwFZq23IatS:-KVWc_7bhwwFZq23IatT:b-9bhqlg) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/README.md#L150)):*
> to the ServerManager module.

to the ServerManager module (provided by default on Windows Server).

---

*[README.md, line 157 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWd-EoDOvP_-JAEEz2:-KVWd-EoDOvP_-JAEEz3:boz45gz) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/README.md#L157)):*
> Set this property to $true to ensure the state of all required subfeatures with the state of the feature you specify with the Name property. The default value is $false.

Specifies whether or not all subfeatures should be installed or uninstalled with the specified role or feature. The default value is false.

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1, line 161 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhbOKU5kMLlb-304o:-KVWhbOKU5kMLlb-304p:b482x1s) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1#L161)):*
> SupportsShouldProcess = $true

This doesn't actually seem to have ShouldProcess anywhere.
Have you run PSSA on this?

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1, line 317 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWdKgDM5N4r_Ju_vzO:-KVWdKgDM5N4r_Ju_vzP:b-m985to) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1#L317)):*
> ```PowerShell
>         As of now, this test can't be used to check if a feature is Installed but all of its
>         subfeatures are uninstalled.
>         By default this is set to $false.
> ```

Specifies whether or not the installation state of all subfeatures should be tested with the specified role or feature. Default is false.
 
If this property is set to true and Ensure is set to Present, each subfeature will be tested to ensure it is installed.
If this property is set to true and Ensure is set to Absent, each subfeature will be tested to ensure it is uninstalled.
If this property is false, subfeatures will not be tested.

(To match the formatting of the Set function)

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.schema.mof, line 7 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWeym61vTgn3_1ZG59:-KVWeym61vTgn3_1ZG5A:b6d1jv5) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.schema.mof#L7)):*
> be installed.

be installed or uninstalled.

---

*[DscResources/MSFT_WindowsFeature/en-US/MSFT_WindowsFeature.schema.mfl, line 1 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhKrufq8z5G4CW0QD:-KVWhKrufq8z5G4CW0QE:bqyjysv) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/en-US/MSFT_WindowsFeature.schema.mfl#L1)):*
> This resource is used to install, uninstall and query roles or features on the DSC managed node.

Please update this description to match the one in the README

---

*[DscResources/MSFT_WindowsFeature/en-US/MSFT_WindowsFeature.schema.mfl, line 6 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWf1GmYyj-2KVUBJj7:-KVWf1GmYyj-2KVUBJj8:b6d1jv5) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/en-US/MSFT_WindowsFeature.schema.mfl#L6)):*
> be installed.

be installed or uninstalled.

---

*[Examples/Sample_WindowsFeature.ps1, line 7 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWf7yDwyisSLnET65_:-KVWf7yDwyisSLnET65a:boq2tq9) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Examples/Sample_WindowsFeature.ps1#L7)):*
> ```PowerShell
>     LogPath and Credential are not included here, but if you would like to specify
>     a custom log path or need a credential just pass in the desired values and add
>     LogPath = $LogPath and/or Credential = $Credential to the configuration here
> ```

Can you change this to be in the normal help-comment format?
With SYNOPSIS and a description of each of the parameters in the configuration?

---

*[Examples/Sample_WindowsFeature.ps1, line 36 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhDtBzyOcCThKUZfo:-KVWhDtBzyOcCThKUZfp:byntcqv) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Examples/Sample_WindowsFeature.ps1#L36)):*
> ```PowerShell
>     
>     Node Localhost {
> ```

Extra line here

---

*[Tests/Integration/MSFT_WindowsFeature.config.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWh84rcOu8vxaYJzUN:-KVWh84rcOu8vxaYJzUO:byntcqv) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.config.ps1#L1)):*
> ```PowerShell
> 
> ```

Extra line here

---

*[Tests/Integration/MSFT_WindowsFeature.config.ps1, line 9 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhBmClWH2v5NHFKMX:-KVWhBmClWH2v5NHFKMY:byntcqv) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.config.ps1#L9)):*
> ```PowerShell
> )
>         
> ```

Extra line here

---

*[Tests/Integration/MSFT_WindowsFeature.config.ps1, line 29 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhAGkUovaAgcKLgm5:-KVWhAGkUovaAgcKLgm6:byntcqv) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.config.ps1#L29)):*
> ```PowerShell
>     
>     Node Localhost {
> ```

Extra line here

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 2 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWgpjtpM2W6NW_ZNi4:-KVWgpjtpM2W6NW_ZNi5:byigmpt) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L2)):*
> for Installing/...

for installing/...

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 23 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWgxJLd_lzIU8SVoYs:-KVWgxJLd_lzIU8SVoYt:b-qpkjtu) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L23)):*
> -Force

There shouldn't be a force on this import

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 32 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWgQcOljZ6fkHle3MV:-KVWgQcOljZ6fkHle3MW:b6icc3r) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L32)):*
> $script:installStateOfTestFeature

$script:installStateOfTestFeature = $false
We should assume the feature is not installed in case Get-WindowsFeature errors out trying to retrieve a feature that has errors or doesn't exist.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 33 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWgl9wWjGZ5bePQ1uy:-KVWgl9wWjGZ5bePQ1uz:b-9nl7s0) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L33)):*
> $script:installStateOfTestWithSubFeatures

$script:installStateOfTestWithSubFeatures = $false
See above comment

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 36 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfzx7GrMaBTtvxVnq:-KVWfzx7GrMaBTtvxVnr:bgwj679) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L36)):*
> that test

for

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 42 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfubmt2XzXkdOmVGf:-KVWfubmt2XzXkdOmVGg:byntcqv) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L42)):*
> ```PowerShell
> 
> try {
> ```

Extra line here

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 53 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfttncDIEF6swtXVZ:-KVWfttncDIEF6swtXV_:byntcqv) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L53)):*
> ```PowerShell
> 
>     Describe 'WindowsFeature Integration Tests' {
> ```

Extra line here

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 99 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfqYPGXR5Kh6nAsmG:-KVWfqYPGXR5Kh6nAsmH:b-fcxaeb) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L99)):*
> ```PowerShell
>             finally
>             {
>                 if (Test-Path -Path $logPath) {
> ```

Bracket on next line

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 148 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfm4fS6i1anlt1O2T:-KVWfm4fS6i1anlt1O2U:b-fcxaeb) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L148)):*
> ```PowerShell
>             finally
>             {
>                 if (Test-Path -Path $logPath) {
> ```

Bracket on next line

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 304 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWffUh7RBvI29QnaYh:-KVWffUh7RBvI29QnaYi:bel4756) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L304)):*
> ```PowerShell
> }
> ```

Extra line or two here

---

*[Tests/Unit/MSFT_WindowsFeature.Tests.ps1, line 17 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfcEA-Rr5LS57yY0S:-KVWfcEA-Rr5LS57yY0T:byntcqv) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Unit/MSFT_WindowsFeature.Tests.ps1#L17)):*
> ```PowerShell
> try {
>     InModuleScope 'MSFT_WindowsFeature' {
> ```

Extra line here

---

*[Tests/Unit/MSFT_WindowsFeature.Tests.ps1, line 28 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfaT9-lm9qlU6YZw6:-KVWfaT9-lm9qlU6YZw7:byntcqv) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Unit/MSFT_WindowsFeature.Tests.ps1#L28)):*
> ```PowerShell
>         $testSubFeatureName2 = 'SubTest2'
>         $testSubFeatureName3 = 'SubTest3'
> ```

Extra line here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/5#-:-KVWaeePls9PHSec-ddJ:b-d0ml7p)*

**Comment by mbreakey3** [comment]
Review status: 0 of 10 files reviewed at latest revision, 25 unresolved discussions.

---

*[README.md, line 1 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWasBIr_1JtEDRQslK:-KVWmEX9mKzhcOajQCO2:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/README.md#L1)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> This badge should represent the test status for the master branch (this is what all the other modules do.
> OR I think it would actually be better to have both the master and the dev branch here so we could also easily see the status of the dev branch at any given time.
> 
> Like this:
> ```
> master: [Build status](https://ci.appveyor.com/project/PowerShell/psdscresources/branch/master)
> 
> dev: [Build status](https://ci.appveyor.com/project/PowerShell/psdscresources/branch/dev)
> ```
</details>
Done.

---

*[README.md, line 150 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWc_7bhwwFZq23IatS:-KVWmZm_AWGQZQ2bWYj7:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/README.md#L150)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > to the ServerManager module.
> 
> to the ServerManager module (provided by default on Windows Server).
</details>
Done.

---

*[README.md, line 157 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWd-EoDOvP_-JAEEz2:-KVWmv7sSJ2ciIN6N2Um:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/README.md#L157)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > Set this property to $true to ensure the state of all required subfeatures with the state of the feature you specify with the Name property. The default value is $false.
> 
> Specifies whether or not all subfeatures should be installed or uninstalled with the specified role or feature. The default value is false.
</details>
Done.

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1, line 161 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhbOKU5kMLlb-304o:-KVWn5tCLCwpcTNYF9SU:b7gi9es) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1#L161)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > SupportsShouldProcess = $true
> 
> This doesn't actually seem to have ShouldProcess anywhere.
> Have you run PSSA on this?
</details>
Yes... but for some reason PSSA hasn't been catching all of my errors

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1, line 317 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWdKgDM5N4r_Ju_vzO:-KVWni_0SeEJnlk3JVuK:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1#L317)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Specifies whether or not the installation state of all subfeatures should be tested with the specified role or feature. Default is false.
>  
> If this property is set to true and Ensure is set to Present, each subfeature will be tested to ensure it is installed.
> If this property is set to true and Ensure is set to Absent, each subfeature will be tested to ensure it is uninstalled.
> If this property is false, subfeatures will not be tested.
> 
> (To match the formatting of the Set function)
</details>
Done.

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.schema.mof, line 7 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWeym61vTgn3_1ZG59:-KVWnvEcLpbtJR8hJvU3:b-20aqg6) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.schema.mof#L7)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > be installed.
> 
> be installed or uninstalled.
</details>
they'll always be uninstalled, no matter if this is specified or not

---

*[DscResources/MSFT_WindowsFeature/en-US/MSFT_WindowsFeature.schema.mfl, line 1 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhKrufq8z5G4CW0QD:-KVWoGgqL7uOuGLxfDM5:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/en-US/MSFT_WindowsFeature.schema.mfl#L1)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > This resource is used to install, uninstall and query roles or features on the DSC managed node.
> 
> Please update this description to match the one in the README
</details>
Done.

---

*[Examples/Sample_WindowsFeature.ps1, line 7 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWf7yDwyisSLnET65_:-KVWqPkQsBH7lF8ae1c8:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Examples/Sample_WindowsFeature.ps1#L7)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Can you change this to be in the normal help-comment format?
> With SYNOPSIS and a description of each of the parameters in the configuration?
</details>
Done.

---

*[Examples/Sample_WindowsFeature.ps1, line 36 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhDtBzyOcCThKUZfo:-KVWqY_hooG2BgHvukvp:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Examples/Sample_WindowsFeature.ps1#L36)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Extra line here
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.config.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWh84rcOu8vxaYJzUN:-KVWqgW5wmxNEuJnmW__:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.config.ps1#L1)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Extra line here
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.config.ps1, line 9 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhBmClWH2v5NHFKMX:-KVWqjXtT9KaiwwcQBhv:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.config.ps1#L9)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Extra line here
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.config.ps1, line 29 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhAGkUovaAgcKLgm5:-KVWqqiYFHBeIv5kiwD7:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.config.ps1#L29)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Extra line here
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 2 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWgpjtpM2W6NW_ZNi4:-KVWqvlzt-4_biojnnNl:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L2)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > for Installing/...
> 
> for installing/...
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 23 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWgxJLd_lzIU8SVoYs:-KVWqyQiHoH_qjMt1ZQj:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L23)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > -Force
> 
> There shouldn't be a force on this import
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 32 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWgQcOljZ6fkHle3MV:-KVWr5Jg439U4KmAPU8h:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L32)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > $script:installStateOfTestFeature
> 
> $script:installStateOfTestFeature = $false
> We should assume the feature is not installed in case Get-WindowsFeature errors out trying to retrieve a feature that has errors or doesn't exist.
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 33 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWgl9wWjGZ5bePQ1uy:-KVWr5ckZe8mGWjGZa9Z:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L33)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > $script:installStateOfTestWithSubFeatures
> 
> $script:installStateOfTestWithSubFeatures = $false
> See above comment
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 36 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfzx7GrMaBTtvxVnq:-KVWrDuzKgMnZXYmcO9o:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L36)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > that test
> 
> for
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 42 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfubmt2XzXkdOmVGf:-KVWrISSaeCBQSOxNYcf:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L42)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Extra line here
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 53 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfttncDIEF6swtXVZ:-KVWrPp3vFXjhXUZznb3:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L53)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Extra line here
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 99 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfqYPGXR5Kh6nAsmG:-KVWrTdB9bwjjkCnZYSq:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L99)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Bracket on next line
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 148 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfm4fS6i1anlt1O2T:-KVWrXwjaOYM0lRlzKz6:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L148)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Bracket on next line
</details>
Done.

---

*[Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1, line 304 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWffUh7RBvI29QnaYh:-KVWrhMPWNr9nkMcgQGK:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Integration/MSFT_WindowsFeature.Integration.Tests.ps1#L304)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Extra line or two here
</details>
Done.

---

*[Tests/Unit/MSFT_WindowsFeature.Tests.ps1, line 17 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfcEA-Rr5LS57yY0S:-KVWrsqdYWtfu4bohAGM:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Unit/MSFT_WindowsFeature.Tests.ps1#L17)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Extra line here
</details>
Done.

---

*[Tests/Unit/MSFT_WindowsFeature.Tests.ps1, line 28 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWfaT9-lm9qlU6YZw6:-KVWs9xoLlaFpUz72jBV:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/Tests/Unit/MSFT_WindowsFeature.Tests.ps1#L28)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Extra line here
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/5)*

**Comment by kwirkykat** [comment]
:lgtm: Just make sure integration tests are all still passing with the rename

---

Reviewed 2 of 9 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1, line 161 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWhbOKU5kMLlb-304o:-KVXI7Bfg9b5z7x9FXDh:b5eobet) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.psm1#L161)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Yes... but for some reason PSSA hasn't been catching all of my errors
</details>
Huh. Weird

---

*[DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.schema.mof, line 7 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWeym61vTgn3_1ZG59:-KVXIFy6GRp_daBVZz20:b-rfncys) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/MSFT_WindowsFeature.schema.mof#L7)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> they'll always be uninstalled, no matter if this is specified or not
</details>
Oh ok. I get it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/5#-:-KVXJws29Lkl4LnFKpEm:b-c8ayhg)*

**Comment by mbreakey3** [comment]
All passing! :D

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[DscResources/MSFT_WindowsFeature/en-US/MSFT_WindowsFeature.schema.mfl, line 6 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/5#-KVWf1GmYyj-2KVUBJj7:-KVXNOmYj5hlIBMRQSRt:b-896fix) ([raw file](https://github.com/powershell/psdscresources/blob/5295ff50b85a20e349e2d871fb2ce34d1f2817e8/DscResources/MSFT_WindowsFeature/en-US/MSFT_WindowsFeature.schema.mfl#L6)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> > be installed.
> 
> be installed or uninstalled.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/5#-:-KVXNL9oUB-D0G_NVa-s:by95pjq)*

**Pull request merged**
