### PR TITLE
Enable CodeCov.io

### PR DESCRIPTION
**Pull request by TravisEz13**
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/35)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[appveyor.yml, line 17 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/35#-Kd-VYBeCRgiZhjVai5c:-Kd-VYBeCRgiZhjVai5d:b-oleisl) ([raw file](https://github.com/powershell/psdscresources/blob/961a4aa595f674a103224d678cfcc1c506c2af36/appveyor.yml#L17)):*
> ```YAML
>             throw 'WMF 5.1 install failed'
>         }
>     - ps: Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
> ```

Why not do this? I know it s one more line:
```yml
   - ps: |
            Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
            Invoke-AppveyorInstallTask
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/35)*

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[appveyor.yml, line 17 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/35#-Kd-VYBeCRgiZhjVai5c:-Kd-W9NHGXiZL8KMryEy:b-rfklgg) ([raw file](https://github.com/powershell/psdscresources/blob/961a4aa595f674a103224d678cfcc1c506c2af36/appveyor.yml#L17)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Why not do this? I know it s one more line:
```yml
   - ps: |
            Import-Module "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
            Invoke-AppveyorInstallTask
```


</blockquote></details>

To be consistent with the style of the existing file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/35)*

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[appveyor.yml, line 17 at r1](https://reviewable.io:443/reviews/powershell/psdscresources/35#-Kd-VYBeCRgiZhjVai5c:-Kd-XFC7ksHViXlfxxPy:bdghj20) ([raw file](https://github.com/powershell/psdscresources/blob/961a4aa595f674a103224d678cfcc1c506c2af36/appveyor.yml#L17)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary><blockquote>

To be consistent with the style of the existing file
</blockquote></details>

@TravisEz13 - ok cool. Just thought I'd check as the other repos (e.g. SharePointDsc, xNetworking) went with the other style.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/35)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/psdscresources/35#-:-Kd-XrImsM8wSzvZCflY:bnfp4nl)*

**Comment by TravisEz13** [comment]
@PlagueHO  this style is needed to support reboots... after we know we are done with the reboot we could switch back to the other style.

**Comment by PlagueHO** [comment]
@TravisEz13 - AHHH! That is excellent info - that may actually explain some issues I've been having in another repo! Thank you!

**Comment by TravisEz13** [comment]
The test failure... I'm not sure why it's happening.  I reran the commit before this one to see if it is an external change or something in this PR.

**Comment by TravisEz13** [comment]
Previous commit failed in a different way without these changes:  https://ci.appveyor.com/project/PowerShell/psdscresources/build/2.4.142.0

**Pull request merged**
