### PR TITLE
Improve speed of Test-IsNanoServer function

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

Currently, the `Test-IsNanoServer` function calls the `Get-ComputerInfo` cmdlet to check with the computer is running Nano server or not. `Get-ComputerInfo` can take 40+ seconds to run each time. This function is called for each user and group resource within a Dsc configuration and therefore can make the Dsc application very slow.

This PR replaces `Get-ComputerInfo` with checking the registry value at `HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Server\ServerLevels\NanoServer`, as documented here: https://msdn.microsoft.com/en-us/library/windows/desktop/hh846315(v=vs.85).aspx

#### This Pull Request (PR) fixes the following issues
None
#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/psdscresources/141)

### CODE REVIEW

**Comment by mhendric** [comment]
Hey @X-Guardian , thanks for the contribution. I was looking through your build log, and it looks like you're failing in xMsiPackage. I've actually been troubleshooting the exact same issue over in xPSDesiredStateConfiguration. I have a fix almost ready to go and will try to submit it this week. I'll do the same in this repo.

The problem seems to occur on machines that default to using only SSL3 and TLS 1.0 for .NET, and the fix is to set SchUseStrongCrypto to true on the test machine, which allows TLS 1.1 and TLS 1.2 to be used.

https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls#schusestrongcrypto

Probable fix:
```
# Make TLS 1.2, TLS 1.1, and TLS 1.0 the default to prevent connection failures on machines
# where [Net.ServicePointManager]::SecurityProtocol is set to Ssl3, Tls
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord -ErrorAction Stop
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord -ErrorAction Stop
```

**Comment by mhendric** [comment]
Opened #142 to track the issue above

**Comment by mhendric** [comment]
Thanks for the updates @X-Guardian . This will need to be re-based, but I suggest waiting until #143 (pending review) is checked in.

**Comment by mhendric** [comment]
Hey @X-Guardian , #143 has now been checked in. Can you rebase and see if that resolves your issue?

**Comment by X-Guardian** [comment]
Hi @mhendric, my branch for this PR seems to have got lost. I've restored the branch on my forked Repo (https://github.com/X-Guardian/PSDscResources/tree/Test-IsNanoServer) but its now not linked to this PR. Anything you can do from your end, or shall I create a new PR?

**Comment by mhendric** [comment]
Hi @X-Guardian . I've never tried this myself, but I think these instructions are pretty close to what you need to do. But these rely on creating a new PR as well. I'm not aware of any way to continue a PR when the original branch is lost (although I'm by no means a Git expert). Creating a new PR is probably the easiest way to get out of this.

https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#how-to-continue-working-on-a-pull-request-pr-when-an-author-contributor-is-unable-to-complete-it

**Comment by X-Guardian** [comment]
Replaced by #154

**Pull request closed without merging**
